---
env: dev
jenkins:
  version: 2.33
  hostname: 127.0.0.1
  http_port: 8080
  https_port: 8443
  admin:
    username: admin
    password: admin
  home: /var/lib/jenkins
  cli: /opt/jenkins-cli.jar
  passwordFileDir: /var/lib/jenkins/secrets
  passwordFileName: initialAdminPassword
  plugins:
    - ansible
    - bitbucket
    - github-pullrequest
    - workflow-aggregator
web:
  hostname: 127.0.0.1
  http_port: 8080
  https_port: 8443
  home: /var/www/
build:
  http_port: 80
  https_port: 443
dev_machine:
  jenkins:
    forwarded_port:
      - guest: "{{ jenkins.http_port }}"
        host: 8080
      # TODO: Create SSL certification by lets encrypt
      # - guest: "{{jenkins.https_port}}"
      #   host:
    shared_folder: []
  web:
    forwarded_port:
      - guest: "{{ web.http_port }}"
        host: 8000
      # TODO: Create SSL certification by lets encrypt
      # - guest: "{{web.https_port}}"
      #   host: 8443
      # LiveReload
      - guest: 35729
        host: 35729
    shared_folder:
      - guest: "{{ web.home }}"
        host: source/web/static
  build:
    forwarded_port:
      - guest: "{{ build.http_port }}"
        host: 80
      # TODO: Create SSL certification by lets encrypt
      # - guest: "{{build.https_port}}"
      #   port: 443
    shared_folder: []
