---
dependencies:
  - role: geerlingguy.homebrew
    homebrew_installed_packages:
    - python3
    when: "ansible_distribution == 'MacOSX'"
  - role: ScorpionResponse.pip
    when: "ansible_distribution != 'MacOSX'"
  - role: geerlingguy.jenkins
    jenkins_version: 2.33
    jenkins_hostname: 127.0.0.1
    jenkins_http_port: 8080
    jenkins_admin_username: admin
    jenkins_admin_password: admin
    jenkins_admin_password_file: /var/lib/jenkins/secrets/initialAdminPassword
    jenkins_home: /var/lib/jenkins
    jenkins_plugins:
      - ansible
      - bitbucket
      - github-pullrequest
      - workflow-aggregator
