---
dependencies:
  - role: geerlingguy.homebrew
    homebrew_installed_packages:
    - python3
    when: "ansible_os_family == 'MacOSX'"
  - role: ScorpionResponse.pip
    when: "ansible_os_family != 'MacOSX'"
