---
dependencies:
  - role: geerlingguy.homebrew
    homebrew_installed_packages:
    - python3
    when: "ansible_distribution == 'MacOSX'"
  - role: ScorpionResponse.pip
    when: "ansible_distribution != 'MacOSX'"
