---
- block:
  - command: whoami
    register: debug

  - debug: msg="{{ debug }}"

  - command: pwd
    register: debug

  - debug: msg="{{ debug }}"

  # - name: LS
  #   command: "ls -l {{ web.home }}"
  #   register: ls

  # - debug: msg="{{ ls }}"

  # TODO: Find out why I can't "cd" into web.home but I can "ls" it.
  # - name: Install package.json
  #   command: npm install
  #   args:
  #     chdir: "{{ web.home }}"

  tags:
  - node
