---
- block:
  - command: whoami
    register: debug

  - debug: msg="{{ debug }}"

  - command: pwd
    register: debug

  - debug: msg="{{ debug }}"

  - name: LS
    command: "ls -l {{ web.home }}"
    register: debug

  - debug: msg="{{ debug }}"

  - name: Install package.json
    local_action: command npm install chdir="{{playbook_dir}}/../source/web/static"

  tags:
  - node
