---
- block:
  - command: "whoami"
    register: debug

  - debug: msg="{{ debug }}"

  - command: "pwd"
    register: debug

  - debug: msg="{{ debug }}"

  - name: LS
    command: "ls -l {{ web.home }}"
    register: ls

  - debug: msg="{{ ls }}"

  - name: Generate directory
    file:
      path: "{{ ansible_env.HOME }}/static"
      state: directory
      mode: 0755

  - name: LS
    command: "ls -a {{ web.home }}"
    register: ls

  - name: Copy from vagrant sync folder
    become: true
    become_user: vagrant
    copy:
      src: /var/www
      dest: "{{ ansible_env.HOME }}/static"

  - name: Change CWD
    command: "cd {{ web.home }}"

  - name: Install package.json
    command: npm install

  tags:
  - node
