---
dependencies:
- role: geerlingguy.nodejs
  nodejs_version: 6
  nodejs_npm_global_packages:
  - nodemon
  - mocha
  - eslint
  when: ansible_distribution == "Ubuntu"
- role: geerlingguy.homebrew
  homebrew_taps: []
  homebrew_installed_packages:
  - node
  homebrew_cask_apps:
  - atom
  when: ansible_distribution == "MacOSX"
