# from galaxy
- src: geerlingguy.homebrew
- src: geerlingguy.jenkins
- src: ScorpionResponse.pip
- src: jgkim.atom
- src: jdauphant.intellij
- src: leonidas.nvm
- src: geerlingguy.java
- src: FGtatsuro.vagrant
