---
- name: Provision Jenkins VM
  hosts: jenkins-{{env}}
  become: True
  roles:
  - jenkins

- name: Provision Web VM
  hosts: "web-{{env}}"
  become: True
  roles:
  - web

- name: Provision Build VM
  hosts: "build-{{env}}"
  roles:
    - angstwad.docker_ubuntu
  become: True
  post_tasks:
  - local_action: command vagrant port {{ item }}
    become: "{{ ansible_user_id }}"
    with_items:
      - jenkins-dev
      - web-dev
      - build-dev
    register: openPorts
  - name: Display vagrant ports
    debug: msg={{ item.stdout }}
    with_items: "{{ openPorts.results }}"
