---
- name: Create directory in case it does not exist.
  file: path={{jenkins.passwordFileDir}} state=directory

- name: Copy password file into location
  template: src=password_file.j2 dest={{jenkins_admin_password_file}}
  become: True

- name: Copy all jobs into target
  copy: src={{item}} dest={{jenkins.jenkins_home}}/jobs
  with_fileglob: "files/jobs/*."
