---
- name: Create directory in case it does not exist.
  file: path=/var/lib/jenkins/secrets state=directory

- name: Copy password file into location
  copy: src=password_file dest=/var/lib/jenkins/secrets/initialAdminPassword
  become: True

- name: Copy all jobs into target
  copy: src={{item}} dest={{jenkins.jenkins_home}}/jobs
  with_fileglob: "files/jobs/*."
