---
dependencies:
  - role: geerlingguy.homebrew
    homebrew_installed_packages:
    - git
    homebrew_cask_apps:
    - visual-studio-code
    - java
    - virtualbox
    - vagrant
    - docker-toolbox
    when: "ansible_distribution == 'MacOSX'"
  - role: FGtatsuro.vagrant
    when: "ansible_distribution != 'MacOSX'"
